### ISSUE TITLE
Error creating the live ISO

### ISSUE THREAD

**Issue by ThePenguinUser** [T-vK/MobilePassThrough#26]
While trying to create the iso using the `./mbpt.sh live build` command, I get an error
Host OS: Fedora 34 (running on a Fedora 35 host in a distrobox container but the same happens on Fedora 35)
The error:
`> Downloading Fedora ISO...
--2022-01-16 16:17:34--  https://download.fedoraproject.org/pub/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso
Resolving download.fedoraproject.org (download.fedoraproject.org)... 67.219.144.68, 185.141.165.254, 38.145.60.20, ...
Connecting to download.fedoraproject.org (download.fedoraproject.org)|67.219.144.68|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mirror.karneval.cz/pub/linux/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso [following]
--2022-01-16 16:17:36--  https://mirror.karneval.cz/pub/linux/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso
Resolving mirror.karneval.cz (mirror.karneval.cz)... 89.102.0.150, 2a02:8301:0:2::150
Connecting to mirror.karneval.cz (mirror.karneval.cz)|89.102.0.150|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2007367680 (1.9G) [application/octet-stream]
Saving to: ‘/home/linux/MobilePassThrough/MobilePassThrough/live-iso-files/Fedora-Workstation-Live-x86_64-34-1.2.iso.part’

/home/linux/MobilePassThrough/MobilePassThrough/live-iso-fi 100%[=========================================================================================================================================>]   1.87G  2.46MB/s    in 14m 9s  

2022-01-16 16:31:45 (2.25 MB/s) - ‘/home/linux/MobilePassThrough/MobilePassThrough/live-iso-files/Fedora-Workstation-Live-x86_64-34-1.2.iso.part’ saved [2007367680/2007367680]

> Rebuilding the ISO adding kernel parameters and some files...
Traceback (most recent call last):
  File "/usr/bin/editliveos", line 74, in <module>
    from imgcreate.fs import *
  File "/usr/lib/python3.9/site-packages/imgcreate/__init__.py", line 19, in <module>
    from imgcreate.live import *
  File "/usr/lib/python3.9/site-packages/imgcreate/live.py", line 35, in <module>
    from imgcreate.fs import *
  File "/usr/lib/python3.9/site-packages/imgcreate/fs.py", line 35, in <module>
    from imgcreate.util import *
  File "/usr/lib/python3.9/site-packages/imgcreate/util.py", line 23, in <module>
    from errors import *
ModuleNotFoundError: No module named 'errors'
mv: cannot stat '/home/linux/MobilePassThrough/MobilePassThrough/live-iso-files/mbpt-*.iso': No such file or directory
`

**Comment by T-vK** [comment]
Interesting, seems like a python module names "errors" is missing? 
Maybe:
pip3 install "errors" 
would do the trick?

**Comment by ThePenguinUser** [comment]
It says ERROR: No matching distribution found for errors, when trying to install the module with pip

**Comment by T-vK** [comment]
https://github.com/livecd-tools/livecd-tools/blob/3fe2b3927e21e8a81c53baae83243100acad3b0c/imgcreate/util.py#L23

That's where this error is coming from. And was added on 9/27/21 https://github.com/livecd-tools/livecd-tools/commit/0cd7cbb29bc079cefec0a4948414942e410c8879#diff-fe6a0d5d44870ace3d1cbd60d610512e5c25f710f56881adbda9a2bc180fb7bc

I suppose this might be a bug on their side. Might be worth it to open an issue on their repo.
Other than that, you might wanna try using an older version of the livecd-tools. The problem is that my script is just cloning the latest version from the master.

**Comment by T-vK** [comment]
The commit I just pushed should fix this issue. If not, feel free to reopen.
