### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by mikemac30** [T-vK/MobilePassThrough#27]
First off I really appreciate the work being done here. Really awesome stuff. However unfortunately, I wasn't able to get this working right away and don't have time to troubleshoot. Is there in easy way to uninstall?

**Comment by T-vK** [comment]
Unfortunately there isn't at the moment. I've thought about, but clean automated uninstall would be extremely complicated if not impossible.

But it's basically just a bunch of installed packages and added kernel parameters. If you undo these, you can delete your MobilePassThrough files. That should be it.

**Comment by mikemac30** [comment]
Okay sweet. I had gone through some tutorials before where people had like services installed in the background and I didn't want to poke around for that.
