### ISSUE TITLE
Is it possible to create a vgpu from amd iGPU?

### ISSUE THREAD

**Issue by Dreaming-Codes** [T-vK/MobilePassThrough#29]
Hi, I would like to know if this feature: 

> Automatically creating a vGPU from the (Intel) iGPU (when the VM starts) to allow sharing the iGPU with the VM (aka "mediated iGPU passthough" using GVT-g) (So your VM can safe a ton of battery life when it doesn't need the dGPU.)

it is also possible for amd iGPU.

My system is AMD + NVIDIA

**Comment by T-vK** [comment]
At the moment this is not supported. I'm not aware that AMD iGPUs even supports this.

**Comment by Dreaming-Codes** [comment]
In fact my question was if AMD iGPUs supports this not if this was supported in this script.
Thanks for your awesome work.
