### ISSUE TITLE
So, have you found any laptop that actually supports GPU Passthrough well?

### ISSUE THREAD

**Issue by vasili111** [T-vK/MobilePassThrough#3]
I am looking at the list at https://gpu-passthrough.com/ and if I understand correctly there is no laptop yet that supports GPU Passthrough we. Did I understand correctly?

**Comment by T-vK** [comment]
Yes and no. The Gigabyte p35x v4 (GTX 980m) did work for me, but I had to create a BIOS mod for it to work. But even then you'll face the issue that most applications don't understand how to talk to the dGPU. And I think thats the exact same thing we saw on the GTX 8xxm and the other 9xxm notebooks on the list that basically worked.
